// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgHRwjRiMbJlSCIaPWb4T_R0BqE2YMcI',
    appId: '1:750569481787:web:158e2648ad4ac94e119e1e',
    messagingSenderId: '750569481787',
    projectId: 'nectar-d9127',
    authDomain: 'nectar-d9127.firebaseapp.com',
    storageBucket: 'nectar-d9127.firebasestorage.app',
    measurementId: 'G-DM2DWVQ50J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbttLyorAqrOzHrg9gYRv5gkY_Ti0Q_0Q',
    appId: '1:750569481787:android:e9feb3b4e0248bb5119e1e',
    messagingSenderId: '750569481787',
    projectId: 'nectar-d9127',
    storageBucket: 'nectar-d9127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGvmqyXXmoLOb3HbQuGyts6hpA3phjcxc',
    appId: '1:750569481787:ios:5efd577aab4f0228119e1e',
    messagingSenderId: '750569481787',
    projectId: 'nectar-d9127',
    storageBucket: 'nectar-d9127.firebasestorage.app',
    iosClientId: '750569481787-e4g3dscu0ncdc8uf5b698i899fq52r6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectarOnlineGrocerietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGvmqyXXmoLOb3HbQuGyts6hpA3phjcxc',
    appId: '1:750569481787:ios:5efd577aab4f0228119e1e',
    messagingSenderId: '750569481787',
    projectId: 'nectar-d9127',
    storageBucket: 'nectar-d9127.firebasestorage.app',
    iosClientId: '750569481787-e4g3dscu0ncdc8uf5b698i899fq52r6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectarOnlineGrocerietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgHRwjRiMbJlSCIaPWb4T_R0BqE2YMcI',
    appId: '1:750569481787:web:447bee7932df4ae3119e1e',
    messagingSenderId: '750569481787',
    projectId: 'nectar-d9127',
    authDomain: 'nectar-d9127.firebaseapp.com',
    storageBucket: 'nectar-d9127.firebasestorage.app',
    measurementId: 'G-0ZG9DRMT6F',
  );
}
